
[font]
size=10


[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[window.padding]
x = 5
y = 5

[cursor.style]
blinking = "always"

[general]
import = [
        "~/.config/alacritty/dracula_plus.toml"
]

[env]
TERM = "xterm-256color"


[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
