bind-key -T copy-mode Enter send-keys -X cancel
bind-key -T copy-mode Escape send-keys -X cancel
set -g mouse on
set -g default-terminal "tmux-256color"
set -as terminal-features ",alacritty:RGB"
set -ag terminal-overrides ",alacritty:Tc"
set -g base-index 1
set -g pane-base-index 1
bind -T prefix s choose-tree -s -Z -K "#{?#{e|<:#{line},9},#{e|+:#{line},1},#{?#{e|<:#{line},36},M-#{a:#{e|+:97,#{e|-:#{line},10}}},}}"
